### ISSUE TITLE
Erro na questão 3

### ISSUE THREAD

**Issue by felipemarinho97** [Guardians-DSC/newbies#2]
No arquivo de log da questão 3 há um pequeno errinho.. uma das saídas do '''strace -T''' saiu da seguinte forma na linha 91 à 93, fugindo do padrão:

> write(1, "ls.log\nREADME\n", 14ls.log
> README
> ) = 14 <0.000012>

**Comment by victorhundo** [comment]
Foi corrigido esse problema, acredito que tenha sido um "ENTER" despercebido. Não corrigimos o erro durante a seleção pra evitar de solicitar que o pessoal que já tinha dado fork tivesse que atualizar seus repositórios com o nosso.

Mas muito obrigado e parabéns pela iniciativa de encontrar o bug e nos avisar! 😄
